// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: usercenter.proto

package server

import (
	"context"

	"CookingMaster_Backend/app/usercenter/rpc/internal/logic"
	"CookingMaster_Backend/app/usercenter/rpc/internal/svc"
	"CookingMaster_Backend/app/usercenter/rpc/usercenter"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	usercenter.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) GenerateToken(ctx context.Context, in *usercenter.GenerateTokenReq) (*usercenter.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

func (s *UsercenterServer) VarifyToken(ctx context.Context, in *usercenter.VarifyTokenReq) (*usercenter.VarifyTokenResp, error) {
	l := logic.NewVarifyTokenLogic(ctx, s.svcCtx)
	return l.VarifyToken(in)
}
