# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary system packages
RUN apt-get update && apt-get install -y

# Set the working directory in the container
WORKDIR /app

# Copy configuration and source files
COPY ./newapp/shopping_list /app

# Install Python dependencies
RUN pip install --no-cache-dir flask mysql-connector-python pyyaml flask-cors

# Expose the application port
EXPOSE 5000

# Start services and run the application
CMD ["python", "shop_list.py"]
