// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ingredientsFieldNames          = builder.RawFieldNames(&Ingredients{})
	ingredientsRows                = strings.Join(ingredientsFieldNames, ",")
	ingredientsRowsExpectAutoSet   = strings.Join(stringx.Remove(ingredientsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ingredientsRowsWithPlaceHolder = strings.Join(stringx.Remove(ingredientsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheIngredientsIdPrefix       = "cache:ingredients:id:"
	cacheIngredientsRecipeIdPrefix = "cache:ingredients:recipeId:"
)

type (
	ingredientsModel interface {
		Insert(ctx context.Context, data *Ingredients) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Ingredients, error)
		FindOneByRecipeId(ctx context.Context, recipeId int64) (*Ingredients, error)
		Update(ctx context.Context, data *Ingredients) error
		Delete(ctx context.Context, id int64) error
	}

	defaultIngredientsModel struct {
		sqlc.CachedConn
		table string
	}

	Ingredients struct {
		Id        int64          `db:"id"`
		RecipeId  int64          `db:"recipe_id"`
		Name      string         `db:"name"`
		Quantity  sql.NullString `db:"quantity"`
		CreatedAt time.Time      `db:"created_at"`
		UpdatedAt time.Time      `db:"updated_at"`
	}
)

func newIngredientsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultIngredientsModel {
	return &defaultIngredientsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`ingredients`",
	}
}

func (m *defaultIngredientsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	ingredientsIdKey := fmt.Sprintf("%s%v", cacheIngredientsIdPrefix, id)
	ingredientsRecipeIdKey := fmt.Sprintf("%s%v", cacheIngredientsRecipeIdPrefix, data.RecipeId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ingredientsIdKey, ingredientsRecipeIdKey)
	return err
}

func (m *defaultIngredientsModel) FindOne(ctx context.Context, id int64) (*Ingredients, error) {
	ingredientsIdKey := fmt.Sprintf("%s%v", cacheIngredientsIdPrefix, id)
	var resp Ingredients
	err := m.QueryRowCtx(ctx, &resp, ingredientsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ingredientsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultIngredientsModel) FindOneByRecipeId(ctx context.Context, recipeId int64) (*Ingredients, error) {
	ingredientsRecipeIdKey := fmt.Sprintf("%s%v", cacheIngredientsRecipeIdPrefix, recipeId)
	var resp Ingredients
	err := m.QueryRowIndexCtx(ctx, &resp, ingredientsRecipeIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `recipe_id` = ? limit 1", ingredientsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, recipeId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultIngredientsModel) Insert(ctx context.Context, data *Ingredients) (sql.Result, error) {
	ingredientsIdKey := fmt.Sprintf("%s%v", cacheIngredientsIdPrefix, data.Id)
	ingredientsRecipeIdKey := fmt.Sprintf("%s%v", cacheIngredientsRecipeIdPrefix, data.RecipeId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, ingredientsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RecipeId, data.Name, data.Quantity)
	}, ingredientsIdKey, ingredientsRecipeIdKey)
	return ret, err
}

func (m *defaultIngredientsModel) Update(ctx context.Context, newData *Ingredients) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	ingredientsIdKey := fmt.Sprintf("%s%v", cacheIngredientsIdPrefix, data.Id)
	ingredientsRecipeIdKey := fmt.Sprintf("%s%v", cacheIngredientsRecipeIdPrefix, data.RecipeId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ingredientsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RecipeId, newData.Name, newData.Quantity, newData.Id)
	}, ingredientsIdKey, ingredientsRecipeIdKey)
	return err
}

func (m *defaultIngredientsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheIngredientsIdPrefix, primary)
}

func (m *defaultIngredientsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ingredientsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultIngredientsModel) tableName() string {
	return m.table
}
