// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	recipesFieldNames          = builder.RawFieldNames(&Recipes{})
	recipesRows                = strings.Join(recipesFieldNames, ",")
	recipesRowsExpectAutoSet   = strings.Join(stringx.Remove(recipesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	recipesRowsWithPlaceHolder = strings.Join(stringx.Remove(recipesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRecipesIdPrefix   = "cache:recipes:id:"
	cacheRecipesNamePrefix = "cache:recipes:name:"
)

type (
	recipesModel interface {
		Insert(ctx context.Context, data *Recipes) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Recipes, error)
		FindOneByName(ctx context.Context, name string) (*Recipes, error)
		Update(ctx context.Context, data *Recipes) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRecipesModel struct {
		sqlc.CachedConn
		table string
	}

	Recipes struct {
		Id          int64          `db:"id"`
		UserId      int64          `db:"user_id"`
		Name        string         `db:"name"`
		Description sql.NullString `db:"description"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newRecipesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRecipesModel {
	return &defaultRecipesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`recipes`",
	}
}

func (m *defaultRecipesModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	recipesIdKey := fmt.Sprintf("%s%v", cacheRecipesIdPrefix, id)
	recipesNameKey := fmt.Sprintf("%s%v", cacheRecipesNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, recipesIdKey, recipesNameKey)
	return err
}

func (m *defaultRecipesModel) FindOne(ctx context.Context, id int64) (*Recipes, error) {
	recipesIdKey := fmt.Sprintf("%s%v", cacheRecipesIdPrefix, id)
	var resp Recipes
	err := m.QueryRowCtx(ctx, &resp, recipesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", recipesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRecipesModel) FindOneByName(ctx context.Context, name string) (*Recipes, error) {
	recipesNameKey := fmt.Sprintf("%s%v", cacheRecipesNamePrefix, name)
	var resp Recipes
	err := m.QueryRowIndexCtx(ctx, &resp, recipesNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", recipesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRecipesModel) Insert(ctx context.Context, data *Recipes) (sql.Result, error) {
	recipesIdKey := fmt.Sprintf("%s%v", cacheRecipesIdPrefix, data.Id)
	recipesNameKey := fmt.Sprintf("%s%v", cacheRecipesNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, recipesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Name, data.Description)
	}, recipesIdKey, recipesNameKey)
	return ret, err
}

func (m *defaultRecipesModel) Update(ctx context.Context, newData *Recipes) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	recipesIdKey := fmt.Sprintf("%s%v", cacheRecipesIdPrefix, data.Id)
	recipesNameKey := fmt.Sprintf("%s%v", cacheRecipesNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, recipesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.Name, newData.Description, newData.Id)
	}, recipesIdKey, recipesNameKey)
	return err
}

func (m *defaultRecipesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRecipesIdPrefix, primary)
}

func (m *defaultRecipesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", recipesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRecipesModel) tableName() string {
	return m.table
}
