// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type LogoutReq struct {
	RefreshToken string `json:"refresh_token"`
}

type LogoutResp struct {
}

type PasswordResetReq struct {
	Email string `json:"email"`
}

type PasswordResetResp struct {
	ResetToken  string `json:"token"`
	ResetExipre int64  `json:"expire"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResp struct {
	RegisterToken  string `json:"token"`
	RegisterExpire string `json:"expire"`
}

type ResetPasswordReq struct {
	ResetToken string `json:"token"`
	Password   string `json:"password"`
}

type ResetPasswordResp struct {
}

type UploadAvatarReq struct {
}

type UploadAvatarResp struct {
	AvatarUrl string `json:"avatar_url"`
}

type User struct {
	UserId    int64  `json:"user_id"`
	Email     string `json:"email"`
	Status    int64  `json:"status"`
	Nickname  string `json:"nickname"`
	Sex       int64  `json:"sex"`
	AvatarUrl string `json:"avatar_url"`
	Info      string `json:"info"`
}

type UserDetailReq struct {
}

type UserDetailResp struct {
	UserDetail User `json:"user"`
}

type UserUpdateReq struct {
	UserDetail User `json:"user"`
}

type UserUpdateResp struct {
}

type VarifyRegisterReq struct {
	RegisterToken string `form:"token"`
}

type VarifyRegisterResp struct {
}
