// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package handler

import (
	"net/http"

	recipe "CookingMaster_Backend/app/recipe/api/internal/handler/recipe"
	"CookingMaster_Backend/app/recipe/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/recipe/delete",
				Handler: recipe.RecipeDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/recipe/detail",
				Handler: recipe.RecipeDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/recipe/insertorupdate",
				Handler: recipe.RecipeInsertOrUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/recipe/list",
				Handler: recipe.RecipeListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/recipe/v1"),
	)
}
