// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type RecipeDeleteReq struct {
	Name string `json:"name"`
}

type RecipeDeleteResp struct {
}

type RecipeDetailReq struct {
	Name string `json:name`
}

type RecipeDetailResp struct {
	Recipe RecipeInfo `json:recipe`
}

type RecipeInfo struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Ingredients []string `json:"ingredients"`
	Quantities  []string `json:"quantities"`
}

type RecipeInsertOrUpdateResp struct {
}

type RecipeInsertoOrUpdateReq struct {
	Recipe RecipeInfo `json:"recipe"`
}

type RecipeListReq struct {
}

type RecipeListResp struct {
	RecipeList []RecipeInfo `json:"recipes"`
}
