name: Test Docker Image

on:
  push:
    paths: ["newapp/**"]
    branches: [ "newapp" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Usercenter Docker image
      run: docker build --tag usercenter -f Dockerfile_usercenter .

    - name: Build Recipe Docker image
      run: docker build --tag recipe -f Dockerfile_recipe .

    - name: Run usercenter container
      run: docker run -d -p 8080:8080 usercenter 

    - name: Run recipe container
      run: docker run -d -p 8081:8081 recipe 

    - name: Test usercenter
      run: |
        docker ps
        curl -X 'POST' \
          'http://localhost:8080/usercenter/v2/register' \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -d '{
          "email": "a@gmail.com",
          "password": "pw"
        }'

    - name: Test recipe
      run: |
        docker ps
        curl -X 'GET' \
          'http://localhost:8081/recipe/v2/list' \
          -H 'accept: application/json'

